### ISSUE TITLE
增强代码的复用性

### ISSUE THREAD

**Issue by JesseYang** [BWZX/crawl-data#1]
股票代码重复出现了两次：
https://github.com/BWZX/crawl-data/blob/master/sharebonus/config.py#L5
https://github.com/BWZX/crawl-data/blob/master/financialstatement/collectData.py#L9
建议只在config中出现，其他地方一律引用config中的

同样的model在代码中重复出现多次，例如：
https://github.com/BWZX/crawl-data/blob/master/financialstatement/mongoModel.py#L18
https://github.com/BWZX/crawl-data/blob/master/sharebonus/mongoModel.py#L18
https://github.com/BWZX/crawl-data/blob/master/stockprice/mongoModel.py#L18
都是Securities的定义，如果表的结构发生改变的话，几个地方都要改，最好还是统一在一个地方定义model，其余地方都引用这个统一的model

**Comment by AdaJass** [comment]
怪我太懒，直接复制粘贴懒写引用代码了

**Comment by AdaJass** [comment]
以后注意
